import 'package:flutter/material.dart';
import 'package:flutterapp/maroappapp/generatedloginwidget/generated/GeneratedRectangle1Widget.dart';
import 'package:flutterapp/maroappapp/generatedloginwidget/generated/GeneratedGroup1Widget.dart';
import 'package:flutterapp/maroappapp/generatedloginwidget/generated/GeneratedRectangle2Widget3.dart';
import 'package:flutterapp/maroappapp/generatedloginwidget/generated/GeneratedBrazilianburger1Widget.dart';
import 'package:flutterapp/maroappapp/generatedloginwidget/generated/GeneratedRectangle3Widget.dart';
import 'package:flutterapp/maroappapp/generatedloginwidget/generated/GeneratedGroup2Widget.dart';
import 'package:flutterapp/maroappapp/generatedloginwidget/generated/GeneratedGroup3Widget1.dart';
import 'package:flutterapp/helpers/transform/transform.dart';
import 'package:flutterapp/maroappapp/generatedloginwidget/generated/GeneratedUserplusWidget.dart';
import 'package:flutterapp/maroappapp/generatedloginwidget/generated/GeneratedUnlockWidget.dart';
import 'package:flutterapp/maroappapp/generatedloginwidget/generated/GeneratedForgotpasscodeWidget.dart';
import 'package:flutterapp/maroappapp/generatedloginwidget/generated/GeneratedLoginWidget1.dart';
import 'package:flutterapp/maroappapp/generatedloginwidget/generated/GeneratedLoginWidget2.dart';
import 'package:flutterapp/maroappapp/generatedloginwidget/generated/GeneratedUnlocktopWidget.dart';
import 'package:flutterapp/maroappapp/generatedloginwidget/generated/GeneratedSignupWidget.dart';

/* Frame Login
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedLoginWidget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.circular(20.0),
      child: Container(
        width: 414.0,
        height: 896.0,
        decoration: BoxDecoration(
          borderRadius: BorderRadius.circular(20.0),
        ),
        child: Stack(
            fit: StackFit.expand,
            alignment: Alignment.center,
            overflow: Overflow.visible,
            children: [
              ClipRRect(
                borderRadius: BorderRadius.circular(20.0),
                child: Container(
                  color: Color.fromARGB(255, 242, 242, 242),
                ),
              ),
              Positioned(
                left: 0.0,
                top: -46.0,
                right: null,
                bottom: null,
                width: 414.0,
                height: 413.0,
                child: GeneratedBrazilianburger1Widget(),
              ),
              Positioned(
                left: 0.0,
                top: -15.0,
                right: null,
                bottom: null,
                width: 414.0,
                height: 382.0,
                child: GeneratedRectangle3Widget(),
              ),
              Positioned(
                left: 111.0,
                top: 52.0,
                right: null,
                bottom: null,
                width: 193.0,
                height: 241.0,
                child: GeneratedGroup3Widget1(),
              ),
              Positioned(
                left: 50.0,
                top: 366.0,
                right: null,
                bottom: null,
                width: 134.0,
                height: 3.0,
                child: GeneratedRectangle1Widget(),
              ),
              Positioned(
                left: 50.0,
                top: 431.0,
                right: null,
                bottom: null,
                width: 314.0,
                height: 59.0,
                child: GeneratedGroup1Widget(),
              ),
              Positioned(
                left: 50.0,
                top: 536.0,
                right: null,
                bottom: null,
                width: 314.0,
                height: 59.0,
                child: GeneratedGroup2Widget(),
              ),
              Positioned(
                left: 50.0,
                top: 629.0,
                right: null,
                bottom: null,
                width: 142.0,
                height: 23.0,
                child: GeneratedForgotpasscodeWidget(),
              ),
              Positioned(
                left: 50.0,
                top: 785.0,
                right: null,
                bottom: null,
                width: 314.0,
                height: 70.0,
                child: GeneratedRectangle2Widget3(),
              ),
              Positioned(
                left: 188.0,
                top: 810.0,
                right: null,
                bottom: null,
                width: 50.0,
                height: 26.0,
                child: GeneratedLoginWidget1(),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: 0.0,
                bottom: 0.0,
                width: null,
                height: null,
                child: LayoutBuilder(builder:
                    (BuildContext context, BoxConstraints constraints) {
                  double percentWidth = 0.03864734299516908;
                  double scaleX = (constraints.maxWidth * percentWidth) / 16.0;

                  double percentHeight = 0.018973214285714284;
                  double scaleY =
                      (constraints.maxHeight * percentHeight) / 17.0;

                  return Stack(children: [
                    TransformHelper.translateAndScale(
                        translateX: constraints.maxWidth * 0.39371980676328505,
                        translateY: constraints.maxHeight * 0.9051339285714286,
                        translateZ: 0,
                        scaleX: scaleX,
                        scaleY: scaleY,
                        scaleZ: 1,
                        child: GeneratedUnlockWidget())
                  ]);
                }),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: 0.0,
                bottom: 0.0,
                width: null,
                height: null,
                child: LayoutBuilder(builder:
                    (BuildContext context, BoxConstraints constraints) {
                  double percentWidth = 0.043478260869565216;
                  double scaleX = (constraints.maxWidth * percentWidth) / 18.0;

                  double percentHeight = 0.015625;
                  double scaleY =
                      (constraints.maxHeight * percentHeight) / 14.0;

                  return Stack(children: [
                    TransformHelper.translateAndScale(
                        translateX: constraints.maxWidth * 0.5748792270531401,
                        translateY: constraints.maxHeight * 0.37388392857142855,
                        translateZ: 0,
                        scaleX: scaleX,
                        scaleY: scaleY,
                        scaleZ: 1,
                        child: GeneratedUserplusWidget())
                  ]);
                }),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: 0.0,
                bottom: 0.0,
                width: null,
                height: null,
                child: LayoutBuilder(builder:
                    (BuildContext context, BoxConstraints constraints) {
                  double percentWidth = 0.028985507246376812;
                  double scaleX = (constraints.maxWidth * percentWidth) / 12.0;

                  double percentHeight = 0.014508928571428572;
                  double scaleY =
                      (constraints.maxHeight * percentHeight) / 13.0;

                  return Stack(children: [
                    TransformHelper.translateAndScale(
                        translateX: constraints.maxWidth * 0.1642512077294686,
                        translateY: constraints.maxHeight * 0.375,
                        translateZ: 0,
                        scaleX: scaleX,
                        scaleY: scaleY,
                        scaleZ: 1,
                        child: GeneratedUnlocktopWidget())
                  ]);
                }),
              ),
              Positioned(
                left: 89.0,
                top: 330.0,
                right: null,
                bottom: null,
                width: 52.0,
                height: 28.0,
                child: GeneratedLoginWidget2(),
              ),
              Positioned(
                left: 263.0,
                top: 330.0,
                right: null,
                bottom: null,
                width: 71.0,
                height: 28.0,
                child: GeneratedSignupWidget(),
              )
            ]),
      ),
    ));
  }
}
