import 'package:flutter/material.dart';
import 'package:flutterapp/maroappapp/generatedmyprofilewidget/generated/GeneratedGroup56Widget.dart';
import 'package:flutterapp/maroappapp/generatedmyprofilewidget/generated/GeneratedGroup60Widget.dart';
import 'package:flutterapp/maroappapp/generatedmyprofilewidget/generated/GeneratedMyprofileWidget1.dart';
import 'package:flutterapp/maroappapp/generatedmyprofilewidget/generated/GeneratedGroup61Widget.dart';
import 'package:flutterapp/maroappapp/generatedmyprofilewidget/generated/GeneratedGroup59Widget.dart';
import 'package:flutterapp/maroappapp/generatedmyprofilewidget/generated/GeneratedChangeWidget1.dart';
import 'package:flutterapp/maroappapp/generatedmyprofilewidget/generated/GeneratedPersonaldetailsWidget.dart';
import 'package:flutterapp/maroappapp/generatedmyprofilewidget/generated/GeneratedGroup58Widget.dart';
import 'package:flutterapp/maroappapp/generatedmyprofilewidget/generated/GeneratedGroup57Widget.dart';
import 'package:flutterapp/maroappapp/generatedmyprofilewidget/generated/GeneratedChevronleftWidget7.dart';

/* Frame My Profile
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedMyProfileWidget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.circular(20.0),
      child: LayoutBuilder(
          builder: (BuildContext context, BoxConstraints constraints) {
        return SingleChildScrollView(
          scrollDirection: Axis.vertical,
          child: Container(
              height: 973.0,
              child: Stack(children: [
                Container(
                    width: constraints.maxWidth,
                    child: Container(
                      width: 414.0,
                      height: 973.0,
                      decoration: BoxDecoration(
                        borderRadius: BorderRadius.circular(20.0),
                      ),
                      child: Stack(
                          fit: StackFit.expand,
                          alignment: Alignment.center,
                          overflow: Overflow.visible,
                          children: [
                            ClipRRect(
                              borderRadius: BorderRadius.circular(20.0),
                              child: Container(
                                color: Color.fromARGB(255, 245, 245, 248),
                              ),
                            ),
                            Positioned(
                              left: 50.0,
                              top: 124.0,
                              right: null,
                              bottom: null,
                              width: 170.0,
                              height: 43.0,
                              child: GeneratedMyprofileWidget1(),
                            ),
                            Positioned(
                              left: 50.0,
                              top: 845.0,
                              right: null,
                              bottom: null,
                              width: 314.0,
                              height: 70.0,
                              child: GeneratedGroup61Widget(),
                            ),
                            Positioned(
                              left: 41.0,
                              top: 60.0,
                              right: null,
                              bottom: null,
                              width: 24.0,
                              height: 24.0,
                              child: GeneratedChevronleftWidget7(),
                            ),
                            Positioned(
                              left: 304.0,
                              top: 212.0,
                              right: null,
                              bottom: null,
                              width: 58.0,
                              height: 23.0,
                              child: GeneratedChangeWidget1(),
                            ),
                            Positioned(
                              left: 42.0,
                              top: 209.0,
                              right: null,
                              bottom: null,
                              width: 144.0,
                              height: 23.0,
                              child: GeneratedPersonaldetailsWidget(),
                            ),
                            Positioned(
                              left: 42.0,
                              top: 241.0,
                              right: null,
                              bottom: null,
                              width: 374.0,
                              height: 197.0,
                              child: GeneratedGroup56Widget(),
                            ),
                            Positioned(
                              left: 42.0,
                              top: 465.0,
                              right: null,
                              bottom: null,
                              width: 315.0,
                              height: 60.0,
                              child: GeneratedGroup57Widget(),
                            ),
                            Positioned(
                              left: 42.0,
                              top: 552.0,
                              right: null,
                              bottom: null,
                              width: 315.0,
                              height: 60.0,
                              child: GeneratedGroup58Widget(),
                            ),
                            Positioned(
                              left: 42.0,
                              top: 639.0,
                              right: null,
                              bottom: null,
                              width: 315.0,
                              height: 60.0,
                              child: GeneratedGroup59Widget(),
                            ),
                            Positioned(
                              left: 42.0,
                              top: 726.0,
                              right: null,
                              bottom: null,
                              width: 315.0,
                              height: 60.0,
                              child: GeneratedGroup60Widget(),
                            )
                          ]),
                    ))
              ])),
        );
      }),
    ));
  }
}
