import 'package:flutter/material.dart';
import 'package:flutterapp/maroappapp/generatedviewpagewidget/generated/GeneratedXcalabresa12Widget.dart';
import 'package:flutterapp/maroappapp/generatedviewpagewidget/generated/GeneratedDeliveredbetweenmondayandfridayfrom2pmto11pminEverettMa.dart';
import 'package:flutterapp/maroappapp/generatedviewpagewidget/generated/GeneratedDeliveryinfoWidget.dart';
import 'package:flutterapp/maroappapp/generatedviewpagewidget/generated/GeneratedHeartWidget1.dart';
import 'package:flutterapp/maroappapp/generatedviewpagewidget/generated/Generated1399Widget7.dart';
import 'package:flutterapp/maroappapp/generatedviewpagewidget/generated/GeneratedChevronleftWidget14.dart';
import 'package:flutterapp/maroappapp/generatedviewpagewidget/generated/GeneratedAllourfoodsaredoublecheckedbeforeleavingourstoressobyan.dart';
import 'package:flutterapp/maroappapp/generatedviewpagewidget/generated/GeneratedXCalabresaWidget10.dart';
import 'package:flutterapp/maroappapp/generatedviewpagewidget/generated/GeneratedDotsWidget.dart';
import 'package:flutterapp/maroappapp/generatedviewpagewidget/generated/GeneratedReturnpolicyWidget.dart';
import 'package:flutterapp/maroappapp/generatedviewpagewidget/generated/Generated\$Widget8.dart';
import 'package:flutterapp/maroappapp/generatedviewpagewidget/generated/GeneratedRectangle2Widget9.dart';
import 'package:flutterapp/maroappapp/generatedviewpagewidget/generated/GeneratedAddtocartWidget.dart';

/* Frame View Page
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedViewPageWidget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.circular(20.0),
      child: Container(
        width: 414.0,
        height: 896.0,
        decoration: BoxDecoration(
          borderRadius: BorderRadius.circular(20.0),
        ),
        child: Stack(
            fit: StackFit.expand,
            alignment: Alignment.center,
            overflow: Overflow.visible,
            children: [
              ClipRRect(
                borderRadius: BorderRadius.circular(20.0),
                child: Container(
                  color: Color.fromARGB(255, 246, 246, 249),
                ),
              ),
              Positioned(
                left: 41.0,
                top: 60.0,
                right: null,
                bottom: null,
                width: 24.0,
                height: 24.0,
                child: GeneratedChevronleftWidget14(),
              ),
              Positioned(
                left: 340.0,
                top: 60.0,
                right: null,
                bottom: null,
                width: 20.0,
                height: 20.0,
                child: GeneratedHeartWidget1(),
              ),
              Positioned(
                left: 126.0,
                top: 441.0,
                right: null,
                bottom: null,
                width: 177.0,
                height: 42.0,
                child: Generated1399Widget7(),
              ),
              Positioned(
                left: 149.0,
                top: 443.0,
                right: null,
                bottom: null,
                width: 23.0,
                height: 29.0,
                child: Generated$Widget8(),
              ),
              Positioned(
                left: 48.0,
                top: 391.0,
                right: null,
                bottom: null,
                width: 320.0,
                height: 54.0,
                child: GeneratedXCalabresaWidget10(),
              ),
              Positioned(
                left: -1.0,
                top: 126.0,
                right: null,
                bottom: null,
                width: 402.0,
                height: 201.0,
                child: GeneratedXcalabresa12Widget(),
              ),
              Positioned(
                left: 53.0,
                top: 506.0,
                right: null,
                bottom: null,
                width: 104.0,
                height: 23.0,
                child: GeneratedDeliveryinfoWidget(),
              ),
              Positioned(
                left: 53.0,
                top: 639.0,
                right: null,
                bottom: null,
                width: 109.0,
                height: 23.0,
                child: GeneratedReturnpolicyWidget(),
              ),
              Positioned(
                left: 53.0,
                top: 534.0,
                right: null,
                bottom: null,
                width: 299.0,
                height: 92.0,
                child:
                    GeneratedDeliveredbetweenmondayandfridayfrom2pmto11pminEverettMa(),
              ),
              Positioned(
                left: 53.0,
                top: 666.0,
                right: null,
                bottom: null,
                width: 299.0,
                height: 160.0,
                child:
                    GeneratedAllourfoodsaredoublecheckedbeforeleavingourstoressobyan(),
              ),
              Positioned(
                left: 172.0,
                top: 355.0,
                right: null,
                bottom: null,
                width: 68.0,
                height: 8.0,
                child: GeneratedDotsWidget(),
              ),
              Positioned(
                left: 50.0,
                top: 785.0,
                right: null,
                bottom: null,
                width: 314.0,
                height: 70.0,
                child: GeneratedRectangle2Widget9(),
              ),
              Positioned(
                left: 160.0,
                top: 810.0,
                right: null,
                bottom: null,
                width: 96.0,
                height: 22.0,
                child: GeneratedAddtocartWidget(),
              )
            ]),
      ),
    ));
  }
}
