import 'package:flutter/material.dart';
import 'package:flutterapp/maroappapp/generatednoordersyetwidget/generated/GeneratedStartoderingWidget1.dart';
import 'package:flutterapp/helpers/transform/transform.dart';
import 'package:flutterapp/maroappapp/generatednoordersyetwidget/generated/GeneratedGroup66Widget.dart';
import 'package:flutterapp/maroappapp/generatednoordersyetwidget/generated/GeneratedRectangle2Widget1.dart';
import 'package:flutterapp/maroappapp/generatednoordersyetwidget/generated/GeneratedChevronleftWidget3.dart';
import 'package:flutterapp/maroappapp/generatednoordersyetwidget/generated/GeneratedOrdersWidget.dart';
import 'package:flutterapp/maroappapp/generatednoordersyetwidget/generated/GeneratedNoordersyetWidget.dart';
import 'package:flutterapp/maroappapp/generatednoordersyetwidget/generated/GeneratedHittheorangebuttondownbelowtoCreateanorderWidget1.dart';

/* Frame No Orders Yet
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedNoOrdersYetWidget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.circular(20.0),
      child: Container(
        width: 414.0,
        height: 896.0,
        decoration: BoxDecoration(
          borderRadius: BorderRadius.circular(20.0),
        ),
        child: Stack(
            fit: StackFit.expand,
            alignment: Alignment.center,
            overflow: Overflow.visible,
            children: [
              ClipRRect(
                borderRadius: BorderRadius.circular(20.0),
                child: Container(
                  color: Color.fromARGB(255, 245, 245, 248),
                ),
              ),
              Positioned(
                left: 175.0,
                top: 61.0,
                right: null,
                bottom: null,
                width: 66.0,
                height: 26.0,
                child: GeneratedOrdersWidget(),
              ),
              Positioned(
                left: 114.0,
                top: 418.0,
                right: null,
                bottom: null,
                width: 188.0,
                height: 35.0,
                child: GeneratedNoordersyetWidget(),
              ),
              Positioned(
                left: 97.0,
                top: 468.0,
                right: null,
                bottom: null,
                width: 222.0,
                height: 42.0,
                child:
                    GeneratedHittheorangebuttondownbelowtoCreateanorderWidget1(),
              ),
              Positioned(
                left: 50.0,
                top: 785.0,
                right: null,
                bottom: null,
                width: 314.0,
                height: 70.0,
                child: GeneratedRectangle2Widget1(),
              ),
              Positioned(
                left: 152.0,
                top: 810.0,
                right: null,
                bottom: null,
                width: 113.0,
                height: 22.0,
                child: GeneratedStartoderingWidget1(),
              ),
              Positioned(
                left: 41.0,
                top: 60.0,
                right: null,
                bottom: null,
                width: 24.0,
                height: 24.0,
                child: GeneratedChevronleftWidget3(),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: 0.0,
                bottom: 0.0,
                width: null,
                height: null,
                child: LayoutBuilder(builder:
                    (BuildContext context, BoxConstraints constraints) {
                  final double width = constraints.maxWidth * 0.273256182094703;

                  final double height =
                      constraints.maxHeight * 0.12051993608474731;

                  return Stack(children: [
                    TransformHelper.translate(
                        x: constraints.maxWidth * 0.32367149758454106,
                        y: constraints.maxHeight * 0.3002232142857143,
                        z: 0,
                        child: Container(
                          width: width,
                          height: height,
                          child: GeneratedGroup66Widget(),
                        ))
                  ]);
                }),
              )
            ]),
      ),
    ));
  }
}
