import 'package:flutter/material.dart';
import 'package:flutterapp/maroappapp/generatedhomewidget/generated/GeneratedVectorWidget38.dart';
import 'package:flutterapp/maroappapp/generatedhomewidget/generated/GeneratedHotDogsWidget.dart';
import 'package:flutterapp/maroappapp/generatedhomewidget/generated/GeneratedGroup4Widget.dart';
import 'package:flutterapp/maroappapp/generatedhomewidget/generated/GeneratedRectangle7Widget.dart';
import 'package:flutterapp/maroappapp/generatedhomewidget/generated/GeneratedHeartWidget.dart';
import 'package:flutterapp/maroappapp/generatedhomewidget/generated/GeneratedSeemoreWidget.dart';
import 'package:flutterapp/maroappapp/generatedhomewidget/generated/GeneratedBurgersWidget.dart';
import 'package:flutterapp/maroappapp/generatedhomewidget/generated/GeneratedVectorWidget37.dart';
import 'package:flutterapp/maroappapp/generatedhomewidget/generated/GeneratedDrinksWidget.dart';
import 'package:flutterapp/maroappapp/generatedhomewidget/generated/GeneratedGroup5Widget.dart';
import 'package:flutterapp/maroappapp/generatedhomewidget/generated/GeneratedWrapsWidget.dart';
import 'package:flutterapp/maroappapp/generatedhomewidget/generated/GeneratedSearchWidget.dart';
import 'package:flutterapp/maroappapp/generatedhomewidget/generated/GeneratedDeliciousfoodforyouWidget.dart';
import 'package:flutterapp/maroappapp/generatedhomewidget/generated/GeneratedShoppingcartWidget.dart';
import 'package:flutterapp/maroappapp/generatedhomewidget/generated/GeneratedIcsharphistoryWidget.dart';
import 'package:flutterapp/maroappapp/generatedhomewidget/generated/GeneratedRectangle1Widget1.dart';
import 'package:flutterapp/maroappapp/generatedhomewidget/generated/GeneratedHeroiconssolidhomeWidget.dart';
import 'package:flutterapp/maroappapp/generatedhomewidget/generated/GeneratedUserWidget.dart';

/* Frame Home
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedHomeWidget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.circular(20.0),
      child: Container(
        width: 414.0,
        height: 896.0,
        decoration: BoxDecoration(
          borderRadius: BorderRadius.circular(20.0),
        ),
        child: Stack(
            fit: StackFit.expand,
            alignment: Alignment.center,
            overflow: Overflow.visible,
            children: [
              ClipRRect(
                borderRadius: BorderRadius.circular(20.0),
                child: Container(
                  color: Color.fromARGB(255, 242, 242, 242),
                ),
              ),
              Positioned(
                left: 50.0,
                top: 132.0,
                right: null,
                bottom: null,
                width: 187.0,
                height: 84.0,
                child: GeneratedDeliciousfoodforyouWidget(),
              ),
              Positioned(
                left: 54.59857177734375,
                top: 74.0,
                right: null,
                bottom: null,
                width: 22.0,
                height: 14.666666030883789,
                child: GeneratedVectorWidget37(),
              ),
              Positioned(
                left: 50.0,
                top: 242.0,
                right: null,
                bottom: null,
                width: 314.0,
                height: 60.0,
                child: GeneratedRectangle7Widget(),
              ),
              Positioned(
                left: 119.0,
                top: 262.0,
                right: null,
                bottom: null,
                width: 61.0,
                height: 26.0,
                child: GeneratedSearchWidget(),
              ),
              Positioned(
                left: 315.0,
                top: 426.0,
                right: null,
                bottom: null,
                width: 60.0,
                height: 20.0,
                child: GeneratedSeemoreWidget(),
              ),
              Positioned(
                left: 88.0,
                top: 348.0,
                right: null,
                bottom: null,
                width: 68.0,
                height: 26.0,
                child: GeneratedBurgersWidget(),
              ),
              Positioned(
                left: 182.0,
                top: 348.0,
                right: null,
                bottom: null,
                width: 56.0,
                height: 26.0,
                child: GeneratedDrinksWidget(),
              ),
              Positioned(
                left: 274.0,
                top: 348.0,
                right: null,
                bottom: null,
                width: 77.0,
                height: 23.0,
                child: GeneratedHotDogsWidget(),
              ),
              Positioned(
                left: 373.0,
                top: 348.0,
                right: null,
                bottom: null,
                width: 57.0,
                height: 26.0,
                child: GeneratedWrapsWidget(),
              ),
              Positioned(
                left: 85.0,
                top: 263.0,
                right: null,
                bottom: null,
                width: 18.0,
                height: 18.0,
                child: GeneratedVectorWidget38(),
              ),
              Positioned(
                left: 39.0,
                top: 464.0,
                right: null,
                bottom: null,
                width: 248.0,
                height: 302.0,
                child: GeneratedGroup4Widget(),
              ),
              Positioned(
                left: 301.0,
                top: 451.0,
                right: null,
                bottom: null,
                width: 220.0,
                height: 315.0,
                child: GeneratedGroup5Widget(),
              ),
              Positioned(
                left: 75.0,
                top: 378.0,
                right: null,
                bottom: null,
                width: 87.0,
                height: 3.0,
                child: GeneratedRectangle1Widget1(),
              ),
              Positioned(
                left: 50.0,
                top: 818.0,
                right: null,
                bottom: null,
                width: 31.0,
                height: 31.0,
                child: GeneratedHeroiconssolidhomeWidget(),
              ),
              Positioned(
                left: 333.0,
                top: 819.0,
                right: null,
                bottom: null,
                width: 29.0,
                height: 29.0,
                child: GeneratedIcsharphistoryWidget(),
              ),
              Positioned(
                left: 349.0,
                top: 65.0,
                right: null,
                bottom: null,
                width: 24.0,
                height: 24.0,
                child: GeneratedShoppingcartWidget(),
              ),
              Positioned(
                left: 241.0,
                top: 822.0,
                right: null,
                bottom: null,
                width: 24.0,
                height: 24.0,
                child: GeneratedUserWidget(),
              ),
              Positioned(
                left: 159.0,
                top: 822.0,
                right: null,
                bottom: null,
                width: 24.0,
                height: 24.0,
                child: GeneratedHeartWidget(),
              )
            ]),
      ),
    ));
  }
}
