import 'package:flutter/material.dart';
import 'package:flutterapp/maroappapp/generatedcheckoutdeliverywidget/generated/GeneratedChevronleftWidget6.dart';
import 'package:flutterapp/maroappapp/generatedcheckoutdeliverywidget/generated/GeneratedDeliveryWidget.dart';
import 'package:flutterapp/maroappapp/generatedcheckoutdeliverywidget/generated/GeneratedRectangle2Widget6.dart';
import 'package:flutterapp/maroappapp/generatedcheckoutdeliverywidget/generated/GeneratedProceedtopaymentWidget.dart';
import 'package:flutterapp/maroappapp/generatedcheckoutdeliverywidget/generated/GeneratedCheckoutWidget.dart';
import 'package:flutterapp/maroappapp/generatedcheckoutdeliverywidget/generated/GeneratedGroup51Widget.dart';
import 'package:flutterapp/maroappapp/generatedcheckoutdeliverywidget/generated/GeneratedGroup50Widget.dart';

/* Frame Checkout - Delivery
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedCheckoutDeliveryWidget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.circular(20.0),
      child: Container(
        width: 414.0,
        height: 896.0,
        decoration: BoxDecoration(
          borderRadius: BorderRadius.circular(20.0),
        ),
        child: Stack(
            fit: StackFit.expand,
            alignment: Alignment.center,
            overflow: Overflow.visible,
            children: [
              ClipRRect(
                borderRadius: BorderRadius.circular(20.0),
                child: Container(
                  color: Color.fromARGB(255, 245, 245, 248),
                ),
              ),
              Positioned(
                left: 161.0,
                top: 61.0,
                right: null,
                bottom: null,
                width: 90.0,
                height: 26.0,
                child: GeneratedCheckoutWidget(),
              ),
              Positioned(
                left: 50.0,
                top: 124.0,
                right: null,
                bottom: null,
                width: 142.0,
                height: 46.0,
                child: GeneratedDeliveryWidget(),
              ),
              Positioned(
                left: 50.0,
                top: 785.0,
                right: null,
                bottom: null,
                width: 314.0,
                height: 70.0,
                child: GeneratedRectangle2Widget6(),
              ),
              Positioned(
                left: 123.0,
                top: 810.0,
                right: null,
                bottom: null,
                width: 170.0,
                height: 22.0,
                child: GeneratedProceedtopaymentWidget(),
              ),
              Positioned(
                left: 41.0,
                top: 60.0,
                right: null,
                bottom: null,
                width: 24.0,
                height: 24.0,
                child: GeneratedChevronleftWidget6(),
              ),
              Positioned(
                left: 50.0,
                top: 210.0,
                right: null,
                bottom: null,
                width: 315.0,
                height: 196.0,
                child: GeneratedGroup50Widget(),
              ),
              Positioned(
                left: 50.0,
                top: 448.0,
                right: null,
                bottom: null,
                width: 318.0,
                height: 289.0,
                child: GeneratedGroup51Widget(),
              )
            ]),
      ),
    ));
  }
}
