import 'package:flutter/material.dart';
import 'package:flutterapp/maroappapp/generatednohistoryyetwidget/generated/GeneratedNohistoryyetWidget.dart';
import 'package:flutterapp/helpers/transform/transform.dart';
import 'package:flutterapp/maroappapp/generatednohistoryyetwidget/generated/GeneratedVectorWidget5.dart';
import 'package:flutterapp/maroappapp/generatednohistoryyetwidget/generated/GeneratedHittheorangebuttondownbelowtoCreateanorderWidget.dart';
import 'package:flutterapp/maroappapp/generatednohistoryyetwidget/generated/GeneratedRectangle2Widget.dart';
import 'package:flutterapp/maroappapp/generatednohistoryyetwidget/generated/GeneratedHistoryWidget.dart';
import 'package:flutterapp/maroappapp/generatednohistoryyetwidget/generated/GeneratedStartoderingWidget.dart';
import 'package:flutterapp/maroappapp/generatednohistoryyetwidget/generated/GeneratedChevronleftWidget2.dart';

/* Frame No History Yet
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedNoHistoryYetWidget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.circular(20.0),
      child: Container(
        width: 414.0,
        height: 896.0,
        decoration: BoxDecoration(
          borderRadius: BorderRadius.circular(20.0),
        ),
        child: Stack(
            fit: StackFit.expand,
            alignment: Alignment.center,
            overflow: Overflow.visible,
            children: [
              ClipRRect(
                borderRadius: BorderRadius.circular(20.0),
                child: Container(
                  color: Color.fromARGB(255, 245, 245, 248),
                ),
              ),
              Positioned(
                left: 175.0,
                top: 61.0,
                right: null,
                bottom: null,
                width: 70.0,
                height: 26.0,
                child: GeneratedHistoryWidget(),
              ),
              Positioned(
                left: 111.0,
                top: 418.0,
                right: null,
                bottom: null,
                width: 195.0,
                height: 35.0,
                child: GeneratedNohistoryyetWidget(),
              ),
              Positioned(
                left: 97.0,
                top: 468.0,
                right: null,
                bottom: null,
                width: 222.0,
                height: 42.0,
                child:
                    GeneratedHittheorangebuttondownbelowtoCreateanorderWidget(),
              ),
              Positioned(
                left: 50.0,
                top: 785.0,
                right: null,
                bottom: null,
                width: 314.0,
                height: 70.0,
                child: GeneratedRectangle2Widget(),
              ),
              Positioned(
                left: 152.0,
                top: 810.0,
                right: null,
                bottom: null,
                width: 113.0,
                height: 22.0,
                child: GeneratedStartoderingWidget(),
              ),
              Positioned(
                left: 41.0,
                top: 60.0,
                right: null,
                bottom: null,
                width: 24.0,
                height: 24.0,
                child: GeneratedChevronleftWidget2(),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: 0.0,
                bottom: 0.0,
                width: null,
                height: null,
                child: LayoutBuilder(builder:
                    (BuildContext context, BoxConstraints constraints) {
                  double percentWidth = 0.2572463768115942;
                  double scaleX = (constraints.maxWidth * percentWidth) / 106.5;

                  double percentHeight = 0.13206846373421804;
                  double scaleY = (constraints.maxHeight * percentHeight) /
                      118.33334350585938;

                  return Stack(children: [
                    TransformHelper.translateAndScale(
                        translateX: constraints.maxWidth * 0.3719806763285024,
                        translateY: constraints.maxHeight * 0.29799107142857145,
                        translateZ: 0,
                        scaleX: scaleX,
                        scaleY: scaleY,
                        scaleZ: 1,
                        child: GeneratedVectorWidget5())
                  ]);
                }),
              )
            ]),
      ),
    ));
  }
}
