import 'package:flutter/material.dart';
import 'package:flutterapp/maroappapp/generatedsearchwidget1/generated/GeneratedRectangle7Widget1.dart';
import 'package:flutterapp/maroappapp/generatedsearchwidget1/generated/GeneratedGroup11Widget1.dart';
import 'package:flutterapp/maroappapp/generatedsearchwidget1/generated/GeneratedGroup10Widget4.dart';
import 'package:flutterapp/maroappapp/generatedsearchwidget1/generated/GeneratedGroup9Widget5.dart';
import 'package:flutterapp/maroappapp/generatedsearchwidget1/generated/GeneratedGroup13Widget.dart';
import 'package:flutterapp/maroappapp/generatedsearchwidget1/generated/GeneratedGroup12Widget.dart';
import 'package:flutterapp/maroappapp/generatedsearchwidget1/generated/GeneratedChevronleftWidget13.dart';
import 'package:flutterapp/maroappapp/generatedsearchwidget1/generated/GeneratedGroup4Widget1.dart';
import 'package:flutterapp/maroappapp/generatedsearchwidget1/generated/GeneratedLine2Widget1.dart';
import 'package:flutterapp/maroappapp/generatedsearchwidget1/generated/GeneratedBrazilianBurgerWidget.dart';
import 'package:flutterapp/maroappapp/generatedsearchwidget1/generated/GeneratedFound19resultsWidget.dart';

/* Frame Search
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedSearchWidget1 extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.circular(20.0),
      child: Container(
        width: 414.0,
        height: 896.0,
        decoration: BoxDecoration(
          borderRadius: BorderRadius.circular(20.0),
        ),
        child: Stack(
            fit: StackFit.expand,
            alignment: Alignment.center,
            overflow: Overflow.visible,
            children: [
              ClipRRect(
                borderRadius: BorderRadius.circular(20.0),
                child: Container(
                  color: Color.fromARGB(255, 238, 238, 238),
                ),
              ),
              Positioned(
                left: 0.0,
                top: 129.0,
                right: null,
                bottom: null,
                width: 414.0,
                height: 811.0,
                child: GeneratedRectangle7Widget1(),
              ),
              Positioned(
                left: 72.0,
                top: 164.0,
                right: null,
                bottom: null,
                width: 272.0,
                height: 37.0,
                child: GeneratedFound19resultsWidget(),
              ),
              Positioned(
                left: 42.0,
                top: 70.0,
                right: null,
                bottom: null,
                width: 24.0,
                height: 24.0,
                child: GeneratedChevronleftWidget13(),
              ),
              Positioned(
                left: 101.0,
                top: 72.0,
                right: null,
                bottom: null,
                width: 134.0,
                height: 23.0,
                child: GeneratedBrazilianBurgerWidget(),
              ),
              Positioned(
                left: 217.0,
                top: 69.0,
                right: null,
                bottom: null,
                width: 26.0,
                height: 1.0,
                child: GeneratedLine2Widget1(),
              ),
              Positioned(
                left: 22.0,
                top: 251.0,
                right: null,
                bottom: null,
                width: 182.0,
                height: 243.0677947998047,
                child: GeneratedGroup4Widget1(),
              ),
              Positioned(
                left: 213.0,
                top: 305.0,
                right: null,
                bottom: null,
                width: 182.0,
                height: 243.0677947998047,
                child: GeneratedGroup9Widget5(),
              ),
              Positioned(
                left: 22.0,
                top: 521.0,
                right: null,
                bottom: null,
                width: 182.0,
                height: 243.0677947998047,
                child: GeneratedGroup10Widget4(),
              ),
              Positioned(
                left: 213.0,
                top: 581.0,
                right: null,
                bottom: null,
                width: 182.0,
                height: 243.0677947998047,
                child: GeneratedGroup11Widget1(),
              ),
              Positioned(
                left: 22.0,
                top: 800.0,
                right: null,
                bottom: null,
                width: 182.0,
                height: 243.0677947998047,
                child: GeneratedGroup12Widget(),
              ),
              Positioned(
                left: 213.0,
                top: 847.0,
                right: null,
                bottom: null,
                width: 182.0,
                height: 243.0677947998047,
                child: GeneratedGroup13Widget(),
              )
            ]),
      ),
    ));
  }
}
