import 'package:flutter/material.dart';
import 'package:flutterapp/maroappapp/generatednoitemfoundwidget/generated/GeneratedTrysearchingtheitemwithadifferentkeywordWidget.dart';
import 'package:flutterapp/maroappapp/generatednoitemfoundwidget/generated/GeneratedFeathersearchWidget.dart';
import 'package:flutterapp/maroappapp/generatednoitemfoundwidget/generated/GeneratedFound6resultsWidget.dart';
import 'package:flutterapp/maroappapp/generatednoitemfoundwidget/generated/GeneratedSpicychiecknsWidget.dart';
import 'package:flutterapp/maroappapp/generatednoitemfoundwidget/generated/GeneratedItemnotfoundWidget.dart';
import 'package:flutterapp/maroappapp/generatednoitemfoundwidget/generated/GeneratedChevronleftWidget.dart';
import 'package:flutterapp/maroappapp/generatednoitemfoundwidget/generated/GeneratedLine2Widget.dart';

/* Frame No Item Found
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedNoItemFoundWidget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.circular(20.0),
      child: Container(
        width: 414.0,
        height: 896.0,
        decoration: BoxDecoration(
          borderRadius: BorderRadius.circular(20.0),
        ),
        child: Stack(
            fit: StackFit.expand,
            alignment: Alignment.center,
            overflow: Overflow.visible,
            children: [
              ClipRRect(
                borderRadius: BorderRadius.circular(20.0),
                child: Container(
                  color: Color.fromARGB(255, 245, 245, 248),
                ),
              ),
              Positioned(
                left: 72.0,
                top: 164.0,
                right: null,
                bottom: null,
                width: 272.0,
                height: 35.0,
                child: GeneratedFound6resultsWidget(),
              ),
              Positioned(
                left: 42.0,
                top: 70.0,
                right: null,
                bottom: null,
                width: 24.0,
                height: 24.0,
                child: GeneratedChevronleftWidget(),
              ),
              Positioned(
                left: 101.0,
                top: 72.0,
                right: null,
                bottom: null,
                width: 115.0,
                height: 22.0,
                child: GeneratedSpicychiecknsWidget(),
              ),
              Positioned(
                left: 217.0,
                top: 69.0,
                right: null,
                bottom: null,
                width: 26.0,
                height: 1.0,
                child: GeneratedLine2Widget(),
              ),
              Positioned(
                left: 107.0,
                top: 445.0,
                right: null,
                bottom: null,
                width: 203.0,
                height: 35.0,
                child: GeneratedItemnotfoundWidget(),
              ),
              Positioned(
                left: 98.0,
                top: 495.0,
                right: null,
                bottom: null,
                width: 220.0,
                height: 42.0,
                child:
                    GeneratedTrysearchingtheitemwithadifferentkeywordWidget(),
              ),
              Positioned(
                left: 131.0,
                top: 285.0,
                right: null,
                bottom: null,
                width: 122.0,
                height: 122.0,
                child: GeneratedFeathersearchWidget(),
              )
            ]),
      ),
    ));
  }
}
