import 'package:flutter/material.dart';
import 'package:flutterapp/maroappapp/generatedopennavwidget/generated/GeneratedArrow1Widget.dart';
import 'package:flutterapp/maroappapp/generatedopennavwidget/generated/GeneratedWhhsecurityaltWidget.dart';
import 'package:flutterapp/maroappapp/generatedopennavwidget/generated/GeneratedLine8Widget.dart';
import 'package:flutterapp/maroappapp/generatedopennavwidget/generated/GeneratedIcoutlinestickynote2Widget.dart';
import 'package:flutterapp/maroappapp/generatedopennavwidget/generated/GeneratedImage10Widget.dart';
import 'package:flutterapp/maroappapp/generatedopennavwidget/generated/GeneratedOfferandpromoWidget.dart';
import 'package:flutterapp/maroappapp/generatedopennavwidget/generated/GeneratedLine5Widget.dart';
import 'package:flutterapp/maroappapp/generatedopennavwidget/generated/GeneratedSignoutWidget.dart';
import 'package:flutterapp/maroappapp/generatedopennavwidget/generated/GeneratedSecurityWidget.dart';
import 'package:flutterapp/maroappapp/generatedopennavwidget/generated/GeneratedPrivacypolicyWidget.dart';
import 'package:flutterapp/maroappapp/generatedopennavwidget/generated/GeneratedProfileWidget.dart';
import 'package:flutterapp/maroappapp/generatedopennavwidget/generated/GeneratedIcoutlinelocalofferWidget.dart';
import 'package:flutterapp/maroappapp/generatedopennavwidget/generated/GeneratedLine7Widget.dart';
import 'package:flutterapp/maroappapp/generatedopennavwidget/generated/GeneratedOrdersWidget2.dart';
import 'package:flutterapp/maroappapp/generatedopennavwidget/generated/GeneratedLine6Widget.dart';
import 'package:flutterapp/maroappapp/generatedopennavwidget/generated/GeneratedGgprofileWidget.dart';
import 'package:flutterapp/maroappapp/generatedopennavwidget/generated/GeneratedImage11Widget.dart';
import 'package:flutterapp/maroappapp/generatedopennavwidget/generated/GeneratedIcons8buyWidget.dart';

/* Frame Open Nav
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedOpenNavWidget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.circular(20.0),
      child: Container(
        width: 414.0,
        height: 896.0,
        decoration: BoxDecoration(
          borderRadius: BorderRadius.circular(20.0),
        ),
        child: Stack(
            fit: StackFit.expand,
            alignment: Alignment.center,
            overflow: Overflow.visible,
            children: [
              ClipRRect(
                borderRadius: BorderRadius.circular(20.0),
                child: Container(
                  color: Color.fromARGB(255, 181, 46, 43),
                ),
              ),
              Positioned(
                left: 233.0276336669922,
                top: 207.19903564453125,
                right: null,
                bottom: null,
                width: 246.09617614746094,
                height: 531.0972900390625,
                child: GeneratedImage11Widget(),
              ),
              Positioned(
                left: 253.75338745117188,
                top: 156.46456909179688,
                right: null,
                bottom: null,
                width: 260.5724182128906,
                height: 562.7640380859375,
                child: GeneratedImage10Widget(),
              ),
              Positioned(
                left: 74.0,
                top: 161.0,
                right: null,
                bottom: null,
                width: 59.0,
                height: 31.0,
                child: GeneratedProfileWidget(),
              ),
              Positioned(
                left: 74.0,
                top: 473.0,
                right: null,
                bottom: null,
                width: 76.0,
                height: 31.0,
                child: GeneratedSecurityWidget(),
              ),
              Positioned(
                left: 74.0,
                top: 239.0,
                right: null,
                bottom: null,
                width: 62.0,
                height: 31.0,
                child: GeneratedOrdersWidget2(),
              ),
              Positioned(
                left: 74.0,
                top: 395.0,
                right: null,
                bottom: null,
                width: 123.0,
                height: 28.0,
                child: GeneratedPrivacypolicyWidget(),
              ),
              Positioned(
                left: 74.0,
                top: 317.0,
                right: null,
                bottom: null,
                width: 143.0,
                height: 28.0,
                child: GeneratedOfferandpromoWidget(),
              ),
              Positioned(
                left: 41.0,
                top: 783.0,
                right: null,
                bottom: null,
                width: 81.0,
                height: 31.0,
                child: GeneratedSignoutWidget(),
              ),
              Positioned(
                left: 129.0,
                top: 797.0,
                right: null,
                bottom: null,
                width: 22.0,
                height: 0.000010490733075130265,
                child: GeneratedArrow1Widget(),
              ),
              Positioned(
                left: 74.0,
                top: 213.0,
                right: null,
                bottom: null,
                width: 132.0,
                height: 0.30000001192092896,
                child: GeneratedLine5Widget(),
              ),
              Positioned(
                left: 74.0,
                top: 291.0,
                right: null,
                bottom: null,
                width: 132.0,
                height: 0.30000001192092896,
                child: GeneratedLine6Widget(),
              ),
              Positioned(
                left: 74.0,
                top: 369.0,
                right: null,
                bottom: null,
                width: 132.0,
                height: 0.30000001192092896,
                child: GeneratedLine7Widget(),
              ),
              Positioned(
                left: 74.0,
                top: 447.0,
                right: null,
                bottom: null,
                width: 132.0,
                height: 0.30000001192092896,
                child: GeneratedLine8Widget(),
              ),
              Positioned(
                left: 38.0,
                top: 162.0,
                right: null,
                bottom: null,
                width: 24.0,
                height: 24.0,
                child: GeneratedGgprofileWidget(),
              ),
              Positioned(
                left: 38.0,
                top: 239.0,
                right: null,
                bottom: null,
                width: 26.0,
                height: 26.0,
                child: GeneratedIcons8buyWidget(),
              ),
              Positioned(
                left: 38.0,
                top: 319.0,
                right: null,
                bottom: null,
                width: 24.0,
                height: 24.0,
                child: GeneratedIcoutlinelocalofferWidget(),
              ),
              Positioned(
                left: 38.0,
                top: 397.0,
                right: null,
                bottom: null,
                width: 24.0,
                height: 24.0,
                child: GeneratedIcoutlinestickynote2Widget(),
              ),
              Positioned(
                left: 38.0,
                top: 476.0,
                right: null,
                bottom: null,
                width: 20.0,
                height: 19.200000762939453,
                child: GeneratedWhhsecurityaltWidget(),
              )
            ]),
      ),
    ));
  }
}
