import 'package:flutter/material.dart';
import 'package:flutterapp/maroappapp/generatedsplashhomewidget/generated/GeneratedEllipse15Widget.dart';
import 'package:flutterapp/maroappapp/generatedsplashhomewidget/generated/GeneratedGroup3Widget.dart';

/* Frame Splash Home
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedSplashHomeWidget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: Visibility(
      visible: false,
      child: ClipRRect(
        borderRadius: BorderRadius.circular(20.0),
        child: Container(
          width: 414.0,
          height: 896.0,
          decoration: BoxDecoration(
            borderRadius: BorderRadius.circular(20.0),
            gradient: LinearGradient(
              begin: Alignment(-1.0, -1.0),
              end: Alignment(0.8599032946495804, 0.9776785513114208),
              stops: [0.0, 1.0],
              colors: [
                Color.fromARGB(255, 255, 255, 255),
                Color.fromARGB(0, 255, 255, 255)
              ],
            ),
          ),
          child: Stack(
              fit: StackFit.expand,
              alignment: Alignment.center,
              overflow: Overflow.visible,
              children: [
                ClipRRect(
                  borderRadius: BorderRadius.circular(20.0),
                  child: Image.asset(
                    "assets/images/90327e64fa0aac45c70f18933e6fd8bdadd0e4f2.png",
                    color: null,
                    fit: BoxFit.cover,
                    width: 414.0,
                    height: 896.0,
                    colorBlendMode: BlendMode.dstATop,
                  ),
                ),
                Positioned(
                  left: 57.0,
                  top: 298.0,
                  right: null,
                  bottom: null,
                  width: 300.0,
                  height: 300.0,
                  child: GeneratedEllipse15Widget(),
                ),
                Positioned(
                  left: 121.77177429199219,
                  top: 337.70465087890625,
                  right: null,
                  bottom: null,
                  width: 173.2282257080078,
                  height: 216.31089782714844,
                  child: GeneratedGroup3Widget(),
                )
              ]),
        ),
      ),
    ));
  }
}
