import 'package:flutter/material.dart';
import 'package:flutterapp/maroappapp/generatedmyprofilepaymentwidget/generated/GeneratedRectangle11Widget.dart';
import 'package:flutterapp/maroappapp/generatedmyprofilepaymentwidget/generated/GeneratedChevronleftWidget4.dart';
import 'package:flutterapp/maroappapp/generatedmyprofilepaymentwidget/generated/GeneratedMyprofileWidget.dart';
import 'package:flutterapp/maroappapp/generatedmyprofilepaymentwidget/generated/GeneratedPaymentMethodWidget.dart';
import 'package:flutterapp/maroappapp/generatedmyprofilepaymentwidget/generated/GeneratedVectorWidget16.dart';
import 'package:flutterapp/maroappapp/generatedmyprofilepaymentwidget/generated/GeneratedRectangle6Widget.dart';
import 'package:flutterapp/maroappapp/generatedmyprofilepaymentwidget/generated/GeneratedMarvisIghedosaWidget.dart';
import 'package:flutterapp/maroappapp/generatedmyprofilepaymentwidget/generated/GeneratedGroup9Widget.dart';
import 'package:flutterapp/maroappapp/generatedmyprofilepaymentwidget/generated/GeneratedCibpaypalWidget.dart';
import 'package:flutterapp/maroappapp/generatedmyprofilepaymentwidget/generated/GeneratedGroup11Widget.dart';
import 'package:flutterapp/maroappapp/generatedmyprofilepaymentwidget/generated/GeneratedRectangle10Widget.dart';
import 'package:flutterapp/maroappapp/generatedmyprofilepaymentwidget/generated/GeneratedDashiconsbankWidget.dart';
import 'package:flutterapp/maroappapp/generatedmyprofilepaymentwidget/generated/GeneratedRectangle2Widget4.dart';
import 'package:flutterapp/maroappapp/generatedmyprofilepaymentwidget/generated/GeneratedBicreditcard2frontfillWidget.dart';
import 'package:flutterapp/maroappapp/generatedmyprofilepaymentwidget/generated/GeneratedUpdatetWidget.dart';
import 'package:flutterapp/maroappapp/generatedmyprofilepaymentwidget/generated/GeneratedNo15utistreetoffoviepalaceroadeffurundeltastateWidget.dart';
import 'package:flutterapp/maroappapp/generatedmyprofilepaymentwidget/generated/GeneratedDosamarvisgmailcomWidget.dart';
import 'package:flutterapp/maroappapp/generatedmyprofilepaymentwidget/generated/GeneratedInformationWidget.dart';
import 'package:flutterapp/maroappapp/generatedmyprofilepaymentwidget/generated/GeneratedGroup10Widget.dart';

/* Frame My Profile - Payment
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedMyProfilePaymentWidget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.circular(20.0),
      child: Container(
        width: 414.0,
        height: 896.0,
        decoration: BoxDecoration(
          borderRadius: BorderRadius.circular(20.0),
        ),
        child: Stack(
            fit: StackFit.expand,
            alignment: Alignment.center,
            overflow: Overflow.visible,
            children: [
              ClipRRect(
                borderRadius: BorderRadius.circular(20.0),
                child: Container(
                  color: Color.fromARGB(255, 245, 245, 248),
                ),
              ),
              Positioned(
                left: 53.0,
                top: 351.0,
                right: null,
                bottom: null,
                width: 144.0,
                height: 22.0,
                child: GeneratedPaymentMethodWidget(),
              ),
              Positioned(
                left: 53.0,
                top: 138.0,
                right: null,
                bottom: null,
                width: 102.0,
                height: 25.0,
                child: GeneratedInformationWidget(),
              ),
              Positioned(
                left: 50.0,
                top: 170.0,
                right: null,
                bottom: null,
                width: 315.0,
                height: 133.0,
                child: GeneratedRectangle10Widget(),
              ),
              Positioned(
                left: 50.0,
                top: 392.0,
                right: null,
                bottom: null,
                width: 315.0,
                height: 231.0,
                child: GeneratedRectangle11Widget(),
              ),
              Positioned(
                left: 161.0,
                top: 61.0,
                right: null,
                bottom: null,
                width: 91.0,
                height: 23.0,
                child: GeneratedMyprofileWidget(),
              ),
              Positioned(
                left: 141.0,
                top: 190.0,
                right: null,
                bottom: null,
                width: 148.0,
                height: 23.0,
                child: GeneratedMarvisIghedosaWidget(),
              ),
              Positioned(
                left: 141.0,
                top: 220.0,
                right: null,
                bottom: null,
                width: 150.0,
                height: 21.0,
                child: GeneratedDosamarvisgmailcomWidget(),
              ),
              Positioned(
                left: 141.0,
                top: 245.0,
                right: null,
                bottom: null,
                width: 193.0,
                height: 34.0,
                child:
                    GeneratedNo15utistreetoffoviepalaceroadeffurundeltastateWidget(),
              ),
              Positioned(
                left: 50.0,
                top: 785.0,
                right: null,
                bottom: null,
                width: 314.0,
                height: 70.0,
                child: GeneratedRectangle2Widget4(),
              ),
              Positioned(
                left: 173.0,
                top: 810.0,
                right: null,
                bottom: null,
                width: 73.0,
                height: 25.0,
                child: GeneratedUpdatetWidget(),
              ),
              Positioned(
                left: 41.0,
                top: 60.0,
                right: null,
                bottom: null,
                width: 24.0,
                height: 24.0,
                child: GeneratedChevronleftWidget4(),
              ),
              Positioned(
                left: 66.0,
                top: 190.0,
                right: null,
                bottom: null,
                width: 60.0,
                height: 60.0,
                child: GeneratedRectangle6Widget(),
              ),
              Positioned(
                left: 71.0,
                top: 412.0,
                right: null,
                bottom: null,
                width: 262.0,
                height: 55.0,
                child: GeneratedGroup9Widget(),
              ),
              Positioned(
                left: 71.0,
                top: 482.0,
                right: null,
                bottom: null,
                width: 262.0,
                height: 55.0,
                child: GeneratedGroup10Widget(),
              ),
              Positioned(
                left: 71.0,
                top: 552.0,
                right: null,
                bottom: null,
                width: 134.0,
                height: 40.0,
                child: GeneratedGroup11Widget(),
              ),
              Positioned(
                left: 114.0,
                top: 423.0,
                right: null,
                bottom: null,
                width: 16.0,
                height: 16.0,
                child: GeneratedBicreditcard2frontfillWidget(),
              ),
              Positioned(
                left: 111.0,
                top: 491.0,
                right: null,
                bottom: null,
                width: 20.0,
                height: 20.0,
                child: GeneratedDashiconsbankWidget(),
              ),
              Positioned(
                left: 113.0,
                top: 564.0,
                right: null,
                bottom: null,
                width: 16.0,
                height: 16.0,
                child: GeneratedCibpaypalWidget(),
              ),
              Positioned(
                left: 320.0,
                top: 197.0,
                right: null,
                bottom: null,
                width: 17.0,
                height: 17.0,
                child: GeneratedVectorWidget16(),
              )
            ]),
      ),
    ));
  }
}
