import 'package:flutter/material.dart';
import 'package:flutterapp/maroappapp/generatedcheckoutpaymentwidget/generated/GeneratedProceedtopaymentWidget1.dart';
import 'package:flutterapp/maroappapp/generatedcheckoutpaymentwidget/generated/GeneratedGroup51Widget1.dart';
import 'package:flutterapp/maroappapp/generatedcheckoutpaymentwidget/generated/GeneratedCheckoutWidget1.dart';
import 'package:flutterapp/maroappapp/generatedcheckoutpaymentwidget/generated/GeneratedGroup52Widget.dart';
import 'package:flutterapp/maroappapp/generatedcheckoutpaymentwidget/generated/GeneratedGroup50Widget1.dart';
import 'package:flutterapp/maroappapp/generatedcheckoutpaymentwidget/generated/GeneratedRectangle2Widget8.dart';
import 'package:flutterapp/maroappapp/generatedcheckoutpaymentwidget/generated/GeneratedChevronleftWidget12.dart';
import 'package:flutterapp/maroappapp/generatedcheckoutpaymentwidget/generated/GeneratedPaymentWidget.dart';

/* Frame Checkout - Payment
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedCheckoutPaymentWidget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.circular(20.0),
      child: Container(
        width: 414.0,
        height: 896.0,
        decoration: BoxDecoration(
          borderRadius: BorderRadius.circular(20.0),
        ),
        child: Stack(
            fit: StackFit.expand,
            alignment: Alignment.center,
            overflow: Overflow.visible,
            children: [
              ClipRRect(
                borderRadius: BorderRadius.circular(20.0),
                child: Container(
                  color: Color.fromARGB(255, 245, 245, 248),
                ),
              ),
              Positioned(
                left: 161.0,
                top: 61.0,
                right: null,
                bottom: null,
                width: 90.0,
                height: 26.0,
                child: GeneratedCheckoutWidget1(),
              ),
              Positioned(
                left: 50.0,
                top: 124.0,
                right: null,
                bottom: null,
                width: 151.0,
                height: 46.0,
                child: GeneratedPaymentWidget(),
              ),
              Positioned(
                left: 50.0,
                top: 785.0,
                right: null,
                bottom: null,
                width: 314.0,
                height: 70.0,
                child: GeneratedRectangle2Widget8(),
              ),
              Positioned(
                left: 123.0,
                top: 810.0,
                right: null,
                bottom: null,
                width: 170.0,
                height: 22.0,
                child: GeneratedProceedtopaymentWidget1(),
              ),
              Positioned(
                left: 41.0,
                top: 60.0,
                right: null,
                bottom: null,
                width: 24.0,
                height: 24.0,
                child: GeneratedChevronleftWidget12(),
              ),
              Positioned(
                left: 50.0,
                top: 711.0,
                right: null,
                bottom: null,
                width: 315.0,
                height: 26.0,
                child: GeneratedGroup51Widget1(),
              ),
              Positioned(
                left: 46.0,
                top: 213.0,
                right: null,
                bottom: null,
                width: 315.0,
                height: 245.0,
                child: GeneratedGroup50Widget1(),
              ),
              Positioned(
                left: 51.0,
                top: 477.0,
                right: null,
                bottom: null,
                width: 315.0,
                height: 196.0,
                child: GeneratedGroup52Widget(),
              )
            ]),
      ),
    ));
  }
}
