import 'package:flutter/material.dart';
import 'package:flutterapp/maroappapp/generatednooffersyetwidget/generated/GeneratedOhhsnapNooffersyetWidget.dart';
import 'package:flutterapp/maroappapp/generatednooffersyetwidget/generated/GeneratedBelladosethaveanyoffersyetpleasecheckagainWidget.dart';
import 'package:flutterapp/maroappapp/generatednooffersyetwidget/generated/GeneratedMyoffersWidget.dart';
import 'package:flutterapp/maroappapp/generatednooffersyetwidget/generated/GeneratedChevronleftWidget1.dart';

/* Frame No Offers Yet
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedNoOffersYetWidget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.circular(20.0),
      child: Container(
        width: 414.0,
        height: 896.0,
        decoration: BoxDecoration(
          borderRadius: BorderRadius.circular(20.0),
        ),
        child: Stack(
            fit: StackFit.expand,
            alignment: Alignment.center,
            overflow: Overflow.visible,
            children: [
              ClipRRect(
                borderRadius: BorderRadius.circular(20.0),
                child: Container(
                  color: Color.fromARGB(255, 245, 245, 248),
                ),
              ),
              Positioned(
                left: 50.0,
                top: 124.0,
                right: null,
                bottom: null,
                width: 144.0,
                height: 53.0,
                child: GeneratedMyoffersWidget(),
              ),
              Positioned(
                left: 41.0,
                top: 60.0,
                right: null,
                bottom: null,
                width: 24.0,
                height: 24.0,
                child: GeneratedChevronleftWidget1(),
              ),
              Positioned(
                left: 47.0,
                top: 488.0,
                right: null,
                bottom: null,
                width: 322.0,
                height: 44.0,
                child: GeneratedOhhsnapNooffersyetWidget(),
              ),
              Positioned(
                left: 91.0,
                top: 538.0,
                right: null,
                bottom: null,
                width: 235.0,
                height: 54.0,
                child:
                    GeneratedBelladosethaveanyoffersyetpleasecheckagainWidget(),
              )
            ]),
      ),
    ));
  }
}
